In [8]:
!pip install clustering-benchmarks -q

In [9]:
import clustbench
data_url = "https://github.com/gagolews/clustering-data-v1/raw/v1.1.0"

In [10]:
battery_datasets_dict = {
                         'fcps': ['atom', 'chainlink', 'engytime', 'hepta', 'lsun', 'target', 'tetra', 'twodiamonds', 'wingnut'],
                         'uci': ['ecoli', 'glass', 'ionosphere', 'sonar', 'statlog', 'wdbc', 'wine', 'yeast'],
                         #'mnist': ['digits', 'fashion'], # Genie digits ~ 32 min
                         #'sipu': ['worms_64'], # Genie ~ 9 min
                         }

| Battery | Dataset    | Rows   | Cols   | Clusters
|---------|------------|--------|--------|----------
| uci     | ecoli      | 336    | 7      | 8
| uci     | glass      | 214    | 9      | 6
| uci     | ionosphere | 351    | 33     | 2
| uci     | sonar      | 208    | 60     | 2
| uci     | statlog    | 2310   | 18     | 7
| uci     | wdbc       | 569    | 30     | 2
| uci     | wine       | 178    | 13     | 3
| uci     | yeast      | 1484   | 8      | 4
| mnist   | digits     | 70000  | 719    | 10
| mnist   | fashion    | 70000  | 784    | 10
| sipu    | worms_64   | 105000 | 64     | 25

In [11]:
import numpy as np
from sklearn.neural_network import MLPRegressor
import pandas as pd

def ssnn_feat_eng(X, n_embeddings=2):

  # To store embeddings for each feature
  embeddings_list = []

  # Get the number of features
  n_samples, n_features = X.shape

  for feature_idx in range(n_features):

      # Prepare input by removing the current feature
      X_in = np.delete(X, feature_idx, axis=1)  # shape: (n_samples, n_features-1)

      # Target is the left-out feature
      y_target = X[:, feature_idx]  # shape: (n_samples,)

      # Define MLP
      mlp = MLPRegressor(
          hidden_layer_sizes=(64, n_embeddings),
          # Use 'identity' for linear activation in the hidden layers
          activation='logistic', #{'relu', 'logistic', 'identity', 'tanh'}
          max_iter=10000,
          random_state=42
      )

      # Fit the model
      mlp.fit(X_in, y_target)

      # Extract learned weights and biases
      coefs = mlp.coefs_
      intercepts = mlp.intercepts_

      # Forward pass to hidden layer 1 (linear)
      Z1 = X_in @ coefs[0] + intercepts[0]  # shape: (n_samples, 64)

      # Forward pass to hidden layer 2 (linear) → this is the embedding
      embeddings = Z1 @ coefs[1] + intercepts[1]  # shape: (n_samples, n_embeddings)

      # Append embeddings
      embeddings_list.append(embeddings)

  # Concatenate all embeddings horizontally
  X_new = np.hstack(embeddings_list)  # shape: (n_samples, n_embeddings * n_features)
  X_new_df = pd.DataFrame(X_new, columns=[f'feature_{i+1}_emb_{j+1}' for i in range(n_features) for j in range(2)])
  return X_new

In [12]:
data_url = "https://github.com/gagolews/clustering-data-v1/raw/v1.1.0"
battery = "uci"
dataset = "statlog"
b = clustbench.load_dataset(battery, dataset, url=data_url)

In [13]:
pd.DataFrame(b.data)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,1.765322,1.035127,0.001837,-0.000088,-0.020114,-0.097886,-0.024911,-0.146012,0.428179,0.372141,0.588547,0.323848,-0.168113,0.481106,-0.312992,0.570538,-0.002047,-0.012852
1,-0.225939,0.124837,-0.000272,-0.000089,-0.030650,-0.103515,-0.039663,-0.149412,-0.685804,-0.622436,-0.789531,-0.645442,0.190103,-0.311184,0.121081,-0.807540,0.010869,-0.014419
2,1.461892,-1.562994,-0.000271,-0.000089,-0.018007,-0.093628,-0.024913,-0.136887,1.630661,1.499467,1.812804,1.579710,-0.393578,0.546428,-0.152850,1.794796,-0.004316,-0.017770
3,-1.762054,0.940305,-0.000272,-0.000090,-0.003257,-0.074487,0.124696,-0.028337,0.124045,0.127710,0.165010,0.079417,0.010995,0.122891,-0.133883,0.147001,-0.003033,-0.012061
4,-1.212087,1.395451,-0.000271,-0.000090,-0.008524,-0.079536,0.003534,-0.119822,0.237831,0.216210,0.329368,0.167918,-0.064862,0.274606,-0.209742,0.311358,-0.002351,-0.012506
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2305,-1.799982,-0.406166,-0.000273,-0.000090,-0.012739,-0.106027,-0.020699,-0.141164,-0.318457,-0.236828,-0.363886,-0.354656,0.244889,-0.136289,-0.108598,-0.381894,-0.000869,-0.003645
2306,0.342993,-1.885388,-0.000272,-0.000090,-0.011686,-0.091065,-0.029128,-0.134702,1.717758,1.609039,1.848626,1.695604,-0.326151,0.392605,-0.066455,1.830617,-0.004882,-0.018706
2307,-0.851764,-0.975098,-0.000271,-0.000090,-0.012739,-0.089239,-0.018590,-0.134197,0.416238,0.351069,0.573797,0.323849,-0.195506,0.472677,-0.277171,0.555789,-0.002129,-0.013793
2308,-0.510405,0.181730,-0.000272,-0.000089,-0.025381,-0.105010,-0.038606,-0.150121,-0.684399,-0.622436,-0.785317,-0.645444,0.185890,-0.302755,0.116867,-0.803327,0.010869,-0.014420
2309,-2.008590,0.447231,-0.000271,-0.000090,-0.031703,-0.106869,-0.036501,-0.154861,-0.623994,-0.548685,-0.711566,-0.611729,0.225924,-0.262720,0.036795,-0.723254,0.005432,-0.002138

In [14]:
autoencoder_feat_eng(b.data)

array([[ 13.81004197, -14.82063806,  -1.39051573, ...,  -0.46980492,
          0.47607998,  -0.50768348],
       [-18.47161276,  18.31404658,  39.59451831, ...,  -0.78837141,
          1.05236506,  -1.09346264],
       [ 66.27576784, -69.36981416, -54.02396342, ...,  -0.20888969,
         -0.42412393,   0.77637578],
       ...,
       [ 11.72831274, -10.58978975, -11.76614186, ...,  -0.52122604,
         -0.17285507,   0.4541925 ],
       [-18.60586915,  18.43868262,  38.46313635, ...,  -0.78995395,
          1.05466575,  -1.09889246],
       [-19.9497942 ,  20.04319461,  30.72918317, ...,  -0.79849741,
          1.02356528,  -1.07582964]])

In [15]:
import genieclust
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

def get_scores(battery, dataset, apply_scale=False):
  b = clustbench.load_dataset(battery, dataset, url=data_url)

  X_transformed = ssnn_feat_eng(b.data)
  if apply_scale:
    # Scale the data
    scaler = StandardScaler()
    X_transformed = scaler.fit_transform(X_transformed)

  g = genieclust.Genie(n_clusters=b.n_clusters[0])
  results = clustbench.fit_predict_many(g, X_transformed, b.n_clusters)
  scores = clustbench.get_score(b.labels, results)

  return scores

In [16]:
import genieclust
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

def get_scores_with_tsne(battery, dataset, apply_scale=False, pca_components=-1, tsne_components=2, tsne_perplexity=30):
  b = clustbench.load_dataset(battery, dataset, url=data_url)

  X_transformed = ssnn_feat_eng(b.data)
  if apply_scale:
    # Scale the data
    scaler = StandardScaler()
    X_transformed = scaler.fit_transform(X_transformed)

  if pca_components != -1:
    pca = PCA(n_components=pca_components)
    X_transformed = pca.fit_transform(X_transformed)

  g = genieclust.Genie(n_clusters=b.n_clusters[0])
  tsne = TSNE(n_components=tsne_components, perplexity=tsne_perplexity, random_state=42) # Reduce to 2 dimensions
  X_transformed = tsne.fit_transform(X_transformed)
  results = clustbench.fit_predict_many(g, X_transformed, b.n_clusters)
  scores = clustbench.get_score(b.labels, results)

  return scores

In [17]:
import genieclust
from umap import UMAP
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

def get_scores_with_umap(battery, dataset, apply_scale=False, pca_components=-1, umap_components=2, n_neighbors=15, min_dist=0.1):
  b = clustbench.load_dataset(battery, dataset, url=data_url)

  X_transformed = ssnn_feat_eng(b.data)
  if apply_scale:
    # Scale the data
    scaler = StandardScaler()
    X_transformed = scaler.fit_transform(X_transformed)

  if pca_components != -1:
    pca = PCA(n_components=pca_components)
    X_transformed = pca.fit_transform(X_transformed)

  g = genieclust.Genie(n_clusters=b.n_clusters[0])
  umap = UMAP(n_components=2, n_neighbors=n_neighbors, min_dist=min_dist, random_state=42, n_jobs=1) # Reduce to 2 dimensions
  X_transformed = umap.fit_transform(X_transformed)
  results = clustbench.fit_predict_many(g, X_transformed, b.n_clusters)
  scores = clustbench.get_score(b.labels, results)

  return scores

In [18]:
import tqdm
import pandas as pd
columns = ['Battery', 'Dataset', 'Genie NCA Score']
df = pd.DataFrame(columns=columns)
scores_lists = {}
for col in columns:
  scores_lists[col] = []

for battery in tqdm.tqdm(battery_datasets_dict.keys(), desc="Processing Batteries"):
  for dataset in tqdm.tqdm(battery_datasets_dict[battery], desc=f"Processing Datasets in {battery}", leave=False):
    scores_lists['Battery'].append(battery)
    scores_lists['Dataset'].append(dataset)
    scores_lists['Genie NCA Score'].append(get_scores(battery, dataset))

df = pd.DataFrame.from_dict(scores_lists)

Processing Batteries:   0%|          | 0/2 [00:00<?, ?it/s]
Processing Datasets in fcps:   0%|          | 0/9 [00:00<?, ?it/s]
Processing Datasets in fcps:  11%|█         | 1/9 [00:01<00:11,  1.44s/it]
Processing Datasets in fcps:  22%|██▏       | 2/9 [00:02<00:08,  1.22s/it]
Processing Datasets in fcps:  33%|███▎      | 3/9 [00:08<00:19,  3.18s/it]
Processing Datasets in fcps:  44%|████▍     | 4/9 [00:08<00:11,  2.22s/it]
Processing Datasets in fcps:  56%|█████▌    | 5/9 [00:09<00:06,  1.52s/it]
Processing Datasets in fcps:  67%|██████▋   | 6/9 [00:09<00:03,  1.11s/it]
Processing Datasets in fcps:  78%|███████▊  | 7/9 [00:10<00:02,  1.03s/it]
Processing Datasets in fcps:  89%|████████▉ | 8/9 [00:10<00:00,  1.25it/s]
Processing Datasets in fcps: 100%|██████████| 9/9 [00:11<00:00,  1.08it/s]
Processing Batteries:  50%|█████     | 1/2 [00:11<00:11, 11.72s/it]
Processing Datasets in uci:   0%|          | 0/8 [00:00<?, ?it/s]
Processing Datasets in uci:  12%|█▎        | 1/8 [00:05<00:38,  5.44s/it]
Processing Datasets in uci:  25%|██▌       | 2/8 [00:05<00:15,  2.56s/it]
Processing Datasets in uci:  38%|███▊      | 3/8 [01:15<02:45, 33.09s/it]
Processing Datasets in uci:  50%|█████     | 4/8 [02:05<02:38, 39.65s/it]
Processing Datasets in uci:  62%|██████▎   | 5/8 [02:50<02:05, 41.86s/it]
Processing Datasets in uci:  75%|███████▌  | 6/8 [03:11<01:09, 34.76s/it]
Processing Datasets in uci:  88%|████████▊ | 7/8 [03:14<00:24, 24.22s/it]
Processing Datasets in uci: 100%|██████████| 8/8 [03:24<00:00, 19.87s/it]
Processing Batteries: 100%|██████████| 2/2 [03:36<00:00, 108.34s/it]

In [19]:
df

   Battery      Dataset  Genie NCA Score
0     fcps         atom         0.977500
1     fcps    chainlink         1.000000
2     fcps     engytime         0.918870
3     fcps        hepta         1.000000
4     fcps         lsun         1.000000
5     fcps       target         1.000000
6     fcps        tetra         0.736667
7     fcps  twodiamonds         0.987500
8     fcps      wingnut         1.000000
9      uci        ecoli         0.405951
10     uci        glass         0.428063
11     uci   ionosphere         0.527937
12     uci        sonar         0.003436
13     uci      statlog         0.587374
14     uci         wdbc         0.743658
15     uci         wine         0.581732
16     uci        yeast         0.203515

In [20]:
tsne_perplexity = [15,30,45]

scores_lists = {}
for perplexity in tqdm.tqdm(tsne_perplexity, desc="Processing TSNE Perplexity"):
  for battery in tqdm.tqdm(battery_datasets_dict.keys(), desc="Processing Batteries"):
    for dataset in tqdm.tqdm(battery_datasets_dict[battery], desc=f"Processing Datasets in {battery}", leave=False):
      column_name = 'Genie+TSNE'+ str(perplexity) +' NCA Score'
      if column_name not in scores_lists:
        scores_lists[column_name] = []
      scores_lists[column_name].append(get_scores_with_tsne(battery, dataset, tsne_perplexity=50))

df_tsne = pd.DataFrame.from_dict(scores_lists)

Processing TSNE Perplexity:   0%|          | 0/3 [00:00<?, ?it/s]
Processing Batteries:   0%|          | 0/2 [00:00<?, ?it/s]

Processing Datasets in fcps:   0%|          | 0/9 [00:00<?, ?it/s]

Processing Datasets in fcps:  11%|█         | 1/9 [00:11<01:29, 11.25s/it]

Processing Datasets in fcps:  22%|██▏       | 2/9 [00:23<01:22, 11.75s/it]

Processing Datasets in fcps:  33%|███▎      | 3/9 [01:21<03:18, 33.11s/it]

Processing Datasets in fcps:  44%|████▍     | 4/9 [01:25<01:46, 21.29s/it]

Processing Datasets in fcps:  56%|█████▌    | 5/9 [01:29<01:00, 15.15s/it]

Processing Datasets in fcps:  67%|██████▋   | 6/9 [01:38<00:39, 13.11s/it]

Processing Datasets in fcps:  78%|███████▊  | 7/9 [01:43<00:20, 10.45s/it]

Processing Datasets in fcps:  89%|████████▉ | 8/9 [01:53<00:10, 10.25s/it]

Processing Datasets in fcps: 100%|██████████| 9/9 [02:06<00:00, 11.27s/it]


Processing Batteries:  50%|█████     | 1/2 [02:06<02:06, 126.77s/it]

Processing Datasets in uci:   0%|          | 0/8 [00:00<?, ?it/s]

Processing Datasets in uci:  12%|█▎        | 1/8 [00:08<00:57,  8.25s/it]

Processing Datasets in uci:  25%|██▌       | 2/8 [00:10<00:29,  4.99s/it]

Processing Datasets in uci:  38%|███▊      | 3/8 [01:21<02:55, 35.13s/it]

Processing Datasets in uci:  50%|█████     | 4/8 [02:09<02:40, 40.08s/it]

Processing Datasets in uci:  62%|██████▎   | 5/8 [03:24<02:38, 52.78s/it]

Processing Datasets in uci:  75%|███████▌  | 6/8 [03:52<01:28, 44.05s/it]

Processing Datasets in uci:  88%|████████▊ | 7/8 [03:56<00:30, 30.98s/it]

Processing Datasets in uci: 100%|██████████| 8/8 [04:30<00:00, 31.93s/it]


Processing Batteries: 100%|██████████| 2/2 [06:36<00:00, 198.42s/it]
Processing TSNE Perplexity:  33%|███▎      | 1/3 [06:36<13:13, 396.84s/it]
Processing Batteries:   0%|          | 0/2 [00:00<?, ?it/s]

Processing Datasets in fcps:   0%|          | 0/9 [00:00<?, ?it/s]

Processing Datasets in fcps:  11%|█         | 1/9 [00:11<01:28, 11.03s/it]

Processing Datasets in fcps:  22%|██▏       | 2/9 [00:22<01:20, 11.49s/it]

Processing Datasets in fcps:  33%|███▎      | 3/9 [01:20<03:15, 32.52s/it]

Processing Datasets in fcps:  44%|████▍     | 4/9 [01:23<01:43, 20.75s/it]

Processing Datasets in fcps:  56%|█████▌    | 5/9 [01:27<00:59, 14.99s/it]

Processing Datasets in fcps:  67%|██████▋   | 6/9 [01:37<00:38, 12.99s/it]

Processing Datasets in fcps:  78%|███████▊  | 7/9 [01:42<00:20, 10.43s/it]

Processing Datasets in fcps:  89%|████████▉ | 8/9 [01:52<00:10, 10.28s/it]

Processing Datasets in fcps: 100%|██████████| 9/9 [02:05<00:00, 11.33s/it]


Processing Batteries:  50%|█████     | 1/2 [02:05<02:05, 125.76s/it]

Processing Datasets in uci:   0%|          | 0/8 [00:00<?, ?it/s]

Processing Datasets in uci:  12%|█▎        | 1/8 [00:07<00:54,  7.83s/it]

Processing Datasets in uci:  25%|██▌       | 2/8 [00:10<00:29,  4.91s/it]

Processing Datasets in uci:  38%|███▊      | 3/8 [01:22<02:56, 35.24s/it]

Processing Datasets in uci:  50%|█████     | 4/8 [02:10<02:42, 40.57s/it]

Processing Datasets in uci:  62%|██████▎   | 5/8 [03:26<02:39, 53.30s/it]

Processing Datasets in uci:  75%|███████▌  | 6/8 [03:54<01:29, 44.57s/it]

Processing Datasets in uci:  88%|████████▊ | 7/8 [03:58<00:31, 31.33s/it]

Processing Datasets in uci: 100%|██████████| 8/8 [04:32<00:00, 32.18s/it]


Processing Batteries: 100%|██████████| 2/2 [06:38<00:00, 199.05s/it]
Processing TSNE Perplexity:  67%|██████▋   | 2/3 [13:14<06:37, 397.58s/it]
Processing Batteries:   0%|          | 0/2 [00:00<?, ?it/s]

Processing Datasets in fcps:   0%|          | 0/9 [00:00<?, ?it/s]

Processing Datasets in fcps:  11%|█         | 1/9 [00:11<01:28, 11.10s/it]

Processing Datasets in fcps:  22%|██▏       | 2/9 [00:22<01:20, 11.53s/it]

Processing Datasets in fcps:  33%|███▎      | 3/9 [01:21<03:17, 32.98s/it]

Processing Datasets in fcps:  44%|████▍     | 4/9 [01:24<01:45, 21.17s/it]

Processing Datasets in fcps:  56%|█████▌    | 5/9 [01:28<01:00, 15.10s/it]

Processing Datasets in fcps:  67%|██████▋   | 6/9 [01:37<00:39, 13.06s/it]

Processing Datasets in fcps:  78%|███████▊  | 7/9 [01:42<00:20, 10.42s/it]

Processing Datasets in fcps:  89%|████████▉ | 8/9 [01:52<00:10, 10.25s/it]

Processing Datasets in fcps: 100%|██████████| 9/9 [02:06<00:00, 11.26s/it]


Processing Batteries:  50%|█████     | 1/2 [02:06<02:06, 126.29s/it]

Processing Datasets in uci:   0%|          | 0/8 [00:00<?, ?it/s]

Processing Datasets in uci:  12%|█▎        | 1/8 [00:07<00:55,  7.90s/it]

Processing Datasets in uci:  25%|██▌       | 2/8 [00:10<00:30,  5.05s/it]

Processing Datasets in uci:  38%|███▊      | 3/8 [01:22<02:56, 35.29s/it]

Processing Datasets in uci:  50%|█████     | 4/8 [02:10<02:41, 40.37s/it]

Processing Datasets in uci:  62%|██████▎   | 5/8 [03:26<02:39, 53.26s/it]

Processing Datasets in uci:  75%|███████▌  | 6/8 [03:53<01:28, 44.44s/it]

Processing Datasets in uci:  88%|████████▊ | 7/8 [03:57<00:31, 31.14s/it]

Processing Datasets in uci: 100%|██████████| 8/8 [04:31<00:00, 32.03s/it]


Processing Batteries: 100%|██████████| 2/2 [06:37<00:00, 198.91s/it]
Processing TSNE Perplexity: 100%|██████████| 3/3 [19:52<00:00, 397.59s/it]

In [21]:
df_tsne

    Genie+TSNE15 NCA Score  Genie+TSNE30 NCA Score  Genie+TSNE45 NCA Score
0                 0.947500                0.947500                0.947500
1                 0.640000                0.640000                0.640000
2                 0.691593                0.691593                0.691593
3                 1.000000                1.000000                1.000000
4                 1.000000                1.000000                1.000000
5                 1.000000                1.000000                1.000000
6                 0.646667                0.646667                0.646667
7                 0.997500                0.997500                0.997500
8                 1.000000                1.000000                1.000000
9                 0.315563                0.311317                0.319559
10                0.391016                0.371886                0.425802
11                0.284127                0.406984                0.239365
12                0.034364                0.034364                0.034364
13                0.526768                0.526768                0.526768
14                0.700875                0.700875                0.700875
15                0.399660                0.581732                0.399660
16                0.164155                0.164155                0.164155

In [22]:
umap_neighbors = [2,10,20,50]

scores_lists = {}
for neighbors in tqdm.tqdm(umap_neighbors, desc="Processing UMAP Neighbors"):
  for battery in tqdm.tqdm(battery_datasets_dict.keys(), desc="Processing Batteries"):
    for dataset in tqdm.tqdm(battery_datasets_dict[battery], desc=f"Processing Datasets in {battery}", leave=False):
      column_name = 'Genie+UMAP'+ str(neighbors) +' NCA Score'
      if column_name not in scores_lists:
        scores_lists[column_name] = []
      scores_lists[column_name].append(get_scores_with_umap(battery, dataset, n_neighbors=neighbors))

df_umap = pd.DataFrame.from_dict(scores_lists)

Processing UMAP Neighbors:   0%|          | 0/4 [00:00<?, ?it/s]
Processing Batteries:   0%|          | 0/2 [00:00<?, ?it/s]

Processing Datasets in fcps:   0%|          | 0/9 [00:00<?, ?it/s]

Processing Datasets in fcps:  11%|█         | 1/9 [00:11<01:35, 11.96s/it]

Processing Datasets in fcps:  22%|██▏       | 2/9 [00:14<00:46,  6.66s/it]/usr/local/lib/python3.12/dist-packages/sklearn/manifold/_spectral_embedding.py:329: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


Processing Datasets in fcps:  33%|███▎      | 3/9 [11:22<30:51, 308.65s/it]

Processing Datasets in fcps:  44%|████▍     | 4/9 [11:23<15:35, 187.18s/it]/usr/local/lib/python3.12/dist-packages/umap/spectral.py:548: UserWarning: Spectral initialisation failed! The eigenvector solver
failed. This is likely due to too small an eigengap. Consider
adding some noise or jitter to your data.

Falling back to random initialisation!
  warn(


Processing Datasets in fcps:  56%|█████▌    | 5/9 [11:24<07:59, 119.99s/it]

Processing Datasets in fcps:  67%|██████▋   | 6/9 [11:27<04:00, 80.07s/it]

Processing Datasets in fcps:  78%|███████▊  | 7/9 [11:28<01:48, 54.33s/it]

Processing Datasets in fcps:  89%|████████▉ | 8/9 [11:30<00:37, 37.56s/it]

Processing Datasets in fcps: 100%|██████████| 9/9 [11:33<00:00, 26.83s/it]


Processing Batteries:  50%|█████     | 1/2 [11:33<11:33, 693.56s/it]

Processing Datasets in uci:   0%|          | 0/8 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/sklearn/manifold/_spectral_embedding.py:329: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


Processing Datasets in uci:  12%|█▎        | 1/8 [00:05<00:37,  5.31s/it]

Processing Datasets in uci:  25%|██▌       | 2/8 [00:06<00:17,  2.87s/it]/usr/local/lib/python3.12/dist-packages/sklearn/manifold/_spectral_embedding.py:329: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


Processing Datasets in uci:  38%|███▊      | 3/8 [01:15<02:44, 32.93s/it]/usr/local/lib/python3.12/dist-packages/sklearn/manifold/_spectral_embedding.py:329: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


Processing Datasets in uci:  50%|█████     | 4/8 [01:59<02:30, 37.55s/it]/usr/local/lib/python3.12/dist-packages/sklearn/manifold/_spectral_embedding.py:329: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


Processing Datasets in uci:  62%|██████▎   | 5/8 [03:49<03:10, 63.66s/it]/usr/local/lib/python3.12/dist-packages/sklearn/manifold/_spectral_embedding.py:329: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


Processing Datasets in uci:  75%|███████▌  | 6/8 [04:10<01:38, 49.10s/it]

Processing Datasets in uci:  88%|████████▊ | 7/8 [04:14<00:34, 34.26s/it]/usr/local/lib/python3.12/dist-packages/sklearn/manifold/_spectral_embedding.py:329: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/manifold/_spectral_embedding.py:455: UserWarning: Exited at iteration 2000 with accuracies
[2.56863624e-15 3.69531519e-06 1.55600498e-06 1.62557836e-05]
not reaching the requested tolerance 5.617737770080566e-06.
Use iteration 1854 instead with accuracy
3.0743578097846078e-06.

  _, diffusion_map = lobpcg(
/usr/local/lib/python3.12/dist-packages/sklearn/manifold/_spectral_embedding.py:455: UserWarning: Exited postprocessing with accuracies
[4.10153632e-15 3.81674672e-06 1.48948262e-06 6.99119377e-06]
not reaching the requested tolerance 5.617737770080566e-06.
  _, diffusion_map = lobpcg(


Processing Datasets in uci: 100%|██████████| 8/8 [04:42<00:00, 32.20s/it]


Processing Batteries: 100%|██████████| 2/2 [16:15<00:00, 487.83s/it]
Processing UMAP Neighbors:  25%|██▌       | 1/4 [16:15<48:47, 975.67s/it]
Processing Batteries:   0%|          | 0/2 [00:00<?, ?it/s]

Processing Datasets in fcps:   0%|          | 0/9 [00:00<?, ?it/s]

Processing Datasets in fcps:  11%|█         | 1/9 [00:02<00:20,  2.58s/it]

Processing Datasets in fcps:  22%|██▏       | 2/9 [00:05<00:20,  2.92s/it]

Processing Datasets in fcps:  33%|███▎      | 3/9 [00:17<00:42,  7.10s/it]

Processing Datasets in fcps:  44%|████▍     | 4/9 [00:18<00:23,  4.74s/it]

Processing Datasets in fcps:  56%|█████▌    | 5/9 [00:19<00:13,  3.39s/it]

Processing Datasets in fcps:  67%|██████▋   | 6/9 [00:22<00:09,  3.21s/it]

Processing Datasets in fcps:  78%|███████▊  | 7/9 [00:24<00:05,  2.65s/it]

Processing Datasets in fcps:  89%|████████▉ | 8/9 [00:26<00:02,  2.40s/it]

Processing Datasets in fcps: 100%|██████████| 9/9 [00:29<00:00,  2.74s/it]


Processing Batteries:  50%|█████     | 1/2 [00:29<00:29, 29.64s/it]

Processing Datasets in uci:   0%|          | 0/8 [00:00<?, ?it/s]

Processing Datasets in uci:  12%|█▎        | 1/8 [00:06<00:44,  6.33s/it]

Processing Datasets in uci:  25%|██▌       | 2/8 [00:07<00:18,  3.10s/it]

Processing Datasets in uci:  38%|███▊      | 3/8 [01:16<02:47, 33.44s/it]

Processing Datasets in uci:  50%|█████     | 4/8 [02:00<02:30, 37.57s/it]

Processing Datasets in uci:  62%|██████▎   | 5/8 [02:56<02:12, 44.16s/it]

Processing Datasets in uci:  75%|███████▌  | 6/8 [03:16<01:12, 36.11s/it]

Processing Datasets in uci:  88%|████████▊ | 7/8 [03:20<00:25, 25.56s/it]

Processing Datasets in uci: 100%|██████████| 8/8 [03:35<00:00, 21.97s/it]


Processing Batteries: 100%|██████████| 2/2 [04:04<00:00, 122.36s/it]
Processing UMAP Neighbors:  50%|█████     | 2/4 [20:20<18:11, 545.71s/it]
Processing Batteries:   0%|          | 0/2 [00:00<?, ?it/s]

Processing Datasets in fcps:   0%|          | 0/9 [00:00<?, ?it/s]

Processing Datasets in fcps:  11%|█         | 1/9 [00:02<00:22,  2.84s/it]

Processing Datasets in fcps:  22%|██▏       | 2/9 [00:06<00:22,  3.25s/it]

Processing Datasets in fcps:  33%|███▎      | 3/9 [00:23<00:57,  9.55s/it]

Processing Datasets in fcps:  44%|████▍     | 4/9 [00:24<00:31,  6.21s/it]

Processing Datasets in fcps:  56%|█████▌    | 5/9 [00:25<00:17,  4.38s/it]

Processing Datasets in fcps:  67%|██████▋   | 6/9 [00:27<00:10,  3.60s/it]

Processing Datasets in fcps:  78%|███████▊  | 7/9 [00:29<00:05,  2.95s/it]

Processing Datasets in fcps:  89%|████████▉ | 8/9 [00:31<00:02,  2.73s/it]

Processing Datasets in fcps: 100%|██████████| 9/9 [00:36<00:00,  3.36s/it]


Processing Batteries:  50%|█████     | 1/2 [00:36<00:36, 36.37s/it]

Processing Datasets in uci:   0%|          | 0/8 [00:00<?, ?it/s]

Processing Datasets in uci:  12%|█▎        | 1/8 [00:05<00:36,  5.19s/it]

Processing Datasets in uci:  25%|██▌       | 2/8 [00:06<00:16,  2.70s/it]

Processing Datasets in uci:  38%|███▊      | 3/8 [01:17<02:51, 34.26s/it]

Processing Datasets in uci:  50%|█████     | 4/8 [02:02<02:32, 38.20s/it]

Processing Datasets in uci:  62%|██████▎   | 5/8 [02:58<02:13, 44.65s/it]

Processing Datasets in uci:  75%|███████▌  | 6/8 [03:20<01:13, 36.92s/it]

Processing Datasets in uci:  88%|████████▊ | 7/8 [03:23<00:25, 25.78s/it]

Processing Datasets in uci: 100%|██████████| 8/8 [03:37<00:00, 22.32s/it]


Processing Batteries: 100%|██████████| 2/2 [04:14<00:00, 127.17s/it]
Processing UMAP Neighbors:  75%|███████▌  | 3/4 [24:34<06:52, 412.67s/it]
Processing Batteries:   0%|          | 0/2 [00:00<?, ?it/s]

Processing Datasets in fcps:   0%|          | 0/9 [00:00<?, ?it/s]

Processing Datasets in fcps:  11%|█         | 1/9 [00:04<00:37,  4.64s/it]

Processing Datasets in fcps:  22%|██▏       | 2/9 [00:08<00:30,  4.38s/it]

Processing Datasets in fcps:  33%|███▎      | 3/9 [00:26<01:03, 10.52s/it]

Processing Datasets in fcps:  44%|████▍     | 4/9 [00:28<00:35,  7.06s/it]

Processing Datasets in fcps:  56%|█████▌    | 5/9 [00:29<00:20,  5.01s/it]

Processing Datasets in fcps:  67%|██████▋   | 6/9 [00:32<00:12,  4.27s/it]

Processing Datasets in fcps:  78%|███████▊  | 7/9 [00:34<00:06,  3.48s/it]

Processing Datasets in fcps:  89%|████████▉ | 8/9 [00:37<00:03,  3.25s/it]

Processing Datasets in fcps: 100%|██████████| 9/9 [00:42<00:00,  4.00s/it]


Processing Batteries:  50%|█████     | 1/2 [00:42<00:42, 42.91s/it]

Processing Datasets in uci:   0%|          | 0/8 [00:00<?, ?it/s]

Processing Datasets in uci:  12%|█▎        | 1/8 [00:05<00:36,  5.26s/it]

Processing Datasets in uci:  25%|██▌       | 2/8 [00:06<00:16,  2.81s/it]

Processing Datasets in uci:  38%|███▊      | 3/8 [01:16<02:47, 33.55s/it]

Processing Datasets in uci:  50%|█████     | 4/8 [02:00<02:31, 37.84s/it]

Processing Datasets in uci:  62%|██████▎   | 5/8 [02:58<02:15, 45.14s/it]

Processing Datasets in uci:  75%|███████▌  | 6/8 [03:20<01:14, 37.25s/it]

Processing Datasets in uci:  88%|████████▊ | 7/8 [03:24<00:26, 26.17s/it]

Processing Datasets in uci: 100%|██████████| 8/8 [03:40<00:00, 23.16s/it]


Processing Batteries: 100%|██████████| 2/2 [04:23<00:00, 131.96s/it]
Processing UMAP Neighbors: 100%|██████████| 4/4 [28:58<00:00, 434.67s/it]

In [23]:
df_umap

,Genie+UMAP2 NCA Score,Genie+UMAP10 NCA Score,Genie+UMAP20 NCA Score,Genie+UMAP50 NCA Score
0,0.267500,0.945000,0.937500,0.940000
1,0.276000,0.500000,1.000000,0.500000
2,0.040599,0.614918,0.922777,0.947721
3,0.262500,1.000000,1.000000,1.000000
4,0.440000,1.000000,1.000000,1.000000
5,0.448160,1.000000,1.000000,1.000000
6,0.230000,0.550000,0.680000,0.783333
7,0.572500,0.997500,0.997500,0.997500
8,0.407480,1.000000,1.000000,1.000000
9,0.278843,0.374418,0.214971,0.251520
10,0.191243,0.360190,0.262826,0.355411
11,0.071746,0.400952,0.432381,0.235873
12,0.025541,0.034364,0.034364,0.034364
13,0.039394,0.444949,0.458586,0.472727
14,0.038885,0.563237,0.563237,0.556247
15,0.192046,0.581732,0.581732,0.581732
16,0.089245,0.158917,0.171662,0.184089

In [24]:
df = pd.concat([df, df_tsne, df_umap], axis=1)
df

,Battery,Dataset,Genie NCA Score,Genie+TSNE15 NCA Score,Genie+TSNE30 NCA Score,Genie+TSNE45 NCA Score,Genie+UMAP2 NCA Score,Genie+UMAP10 NCA Score,Genie+UMAP20 NCA Score,Genie+UMAP50 NCA Score
0,fcps,atom,0.977500,0.947500,0.947500,0.947500,0.267500,0.945000,0.937500,0.940000
1,fcps,chainlink,1.000000,0.640000,0.640000,0.640000,0.276000,0.500000,1.000000,0.500000
2,fcps,engytime,0.918870,0.691593,0.691593,0.691593,0.040599,0.614918,0.922777,0.947721
3,fcps,hepta,1.000000,1.000000,1.000000,1.000000,0.262500,1.000000,1.000000,1.000000
4,fcps,lsun,1.000000,1.000000,1.000000,1.000000,0.440000,1.000000,1.000000,1.000000
5,fcps,target,1.000000,1.000000,1.000000,1.000000,0.448160,1.000000,1.000000,1.000000
6,fcps,tetra,0.736667,0.646667,0.646667,0.646667,0.230000,0.550000,0.680000,0.783333
7,fcps,twodiamonds,0.987500,0.997500,0.997500,0.997500,0.572500,0.997500,0.997500,0.997500
8,fcps,wingnut,1.000000,1.000000,1.000000,1.000000,0.407480,1.000000,1.000000,1.000000
9,uci,ecoli,0.405951,0.315563,0.311317,0.319559,0.278843,0.374418,0.214971,0.251520
10,uci,glass,0.428063,0.391016,0.371886,0.425802,0.191243,0.360190,0.262826,0.355411
11,uci,ionosphere,0.527937,0.284127,0.406984,0.239365,0.071746,0.400952,0.432381,0.235873
12,uci,sonar,0.003436,0.034364,0.034364,0.034364,0.025541,0.034364,0.034364,0.034364
13,uci,statlog,0.587374,0.526768,0.526768,0.526768,0.039394,0.444949,0.458586,0.472727
14,uci,wdbc,0.743658,0.700875,0.700875,0.700875,0.038885,0.563237,0.563237,0.556247
15,uci,wine,0.581732,0.399660,0.581732,0.399660,0.192046,0.581732,0.581732,0.581732
16,uci,yeast,0.203515,0.164155,0.164155,0.164155,0.089245,0.158917,0.171662,0.184089

In [26]:
cols_to_display = ['Battery','Dataset','Genie NCA Score',	'Genie+TSNE15 NCA Score',	'Genie+TSNE30 NCA Score',	'Genie+TSNE45 NCA Score', 'Genie+UMAP2 NCA Score',	'Genie+UMAP10 NCA Score',	'Genie+UMAP20 NCA Score',	'Genie+UMAP50 NCA Score']
numerical_cols = ['Genie NCA Score',	'Genie+TSNE15 NCA Score',	'Genie+TSNE30 NCA Score',	'Genie+TSNE45 NCA Score', 'Genie+UMAP2 NCA Score',	'Genie+UMAP10 NCA Score',	'Genie+UMAP20 NCA Score',	'Genie+UMAP50 NCA Score']
df[cols_to_display].style.highlight_max(axis=1, subset=numerical_cols)